### ISSUE TITLE
hmmmm

### ISSUE THREAD

**Issue by nicmcd** [gaomy3832/utils#1]
random.h looks strikingly similar to the code here:
https://github.com/nicmcd/librnd

**Comment by gaomy3832** [comment]
Hi Nic, I would admit that I definitely referred to some existing code (highly likely yours :) ) and just put them together to make it convenient to use. I actually haven't used this set of utilities for a while. I can remove it if you are uncomfortable with it. Let me know :)

**Comment by nicmcd** [comment]
No worries, I’m just giving you a hard time.
